config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # パートナーの一覧ページとネスト
  resources :partners do
    member do
      delete :remove_image
      post :create_token  # 特定のパートナーに対する追加
      post :remove_share
    end
    collection do
      post :create_token  # 全てのパートナーに対する追加
    end
    resources :medications do
      member do
        delete :remove_image
      end
    end
    resources :foods do
      member do
        delete :remove_image
      end
    end
    resources :walks, only: %i[edit update]
  end

  # /complete_tutorial 等を独立したルートとして定義（本来partnersやsettingsと関係ないため）
  post 'complete_tutorial', to: 'partners#complete_tutorial', as: 'complete_tutorial'
  post 'reset_tutorial', to: 'settings#reset_tutorial', as: 'reset_tutorial'

  # ユーザー登録関連
  resources :users, only: %i[new create destroy]
  get 'users/delete', to: 'users#delete', as: :delete_user

  # ログイン・ログアウト関連
  resources :user_sessions, only: %i[new create destroy]
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # TOPページ（partners#indexに設定）
  root to: 'partners#index'

  # ログインページを明示的に設定
  get 'login', to: 'user_sessions#new'

  # 設定ページ
  resource :settings, only: %i[show update] do
    get :name_change, on: :collection
    get :news, on: :collection
    get :privacy_policy, on: :collection
    get :terms_of_use, on: :collection
  end

  # 開発環境でのメール設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :password_resets, only: %i[new create edit update]

  resources :email_changes, only: %i[new create update] do
    get 'confirm', on: :member
  end

  resources :remainders, only: [:update]

  namespace :api do
    resources :device_tokens, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]

  get 'share/:token', to: 'partner_shares#confirm', as: :confirm_share
  delete 'mutual_unshare/:user_id', to: 'partner_shares#mutual_unshare', as: :mutual_unshare
  delete 'other_partner_unshare/:user_id', to: 'partner_shares#other_partner_unshare', as: :other_partner_unshare
  delete 'my_partner_unshare/:user_id', to: 'partner_shares#my_partner_unshare', as: :my_partner_unshare

  # SNSログイン
  get '/auth/:provider/callback', to: 'sns_logins#create'
end

app/models/user.rb
# frozen_string_literal: true

# ユーザーの新規登録に関するモデルです。
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :partners, foreign_key: :owner_id,
                      dependent: :destroy, inverse_of: :owner
  has_many :tokens, dependent: :destroy
  has_many :partner_shares, dependent: :destroy, inverse_of: :user
  has_many :shared_partner_shares, class_name: 'PartnerShare', foreign_key: :shared_by, inverse_of: :shared_by_user,
                                   dependent: :destroy
  has_many :device_tokens, dependent: :destroy

  # バリデーションを追加
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :new_email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_nil: true
  validates :email_change_token, uniqueness: true, allow_nil: true

  def partners_with_shared
    own_partners = partners.includes(:owner).with_attached_image
    shared_partners = Partner.joins(:partner_shares)
                             .where(partner_shares: { shared_by: id })
                             .includes(:owner).with_attached_image

    # 自分のペットを優先的に表示
    (own_partners + shared_partners).uniq.sort_by do |partner|
      partner.owner_id == id ? 0 : 1
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザーの新規登録に関するコントローラーです。
class UsersController < ApplicationController
  skip_before_action :require_login
  skip_before_action :auto_login_with_remember_me

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user) # Sorceryの自動ログインメソッドを呼び出し
      flash[:success] = 'ユーザー登録が完了しました'
      redirect_to root_path
    else
      Rails.logger.debug "User save failed: #{@user.errors.full_messages}"
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def delete; end

  def destroy
    if current_user
      if current_user.destroy
        flash[:success] = 'アカウントを削除しました。'
        redirect_to login_path
      else
        flash[:danger] = 'アカウント削除に失敗しました。'
        redirect_to settings_path
      end
    else
      flash[:alert] = 'ログインが必要です。'
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# ユーザーの新規登録について使用されるヘルパーメソッドを提供します。
module UsersHelper
end

app/views/users/delete.html.erb
<% @page_title = "アカウント削除" %>

<div class="container mt-5">
  <div class="row">
    <div class="col-11 col-md-6 mx-auto">

        <h5>アカウント削除の確認</h5>
        <hr>
        <p>本当にアカウントを削除しますか？</p>
        <p>アカウントを削除するとすべてのデータが消えます。元に戻すことはできません。了承の上、削除ください。</p>
        <div class="d-flex gap-2">
        <% if current_user %>
            <%= button_to '削除する', user_path(current_user), method: :delete, 
                data: { confirm: '本当に削除しますか？' }, 
                class: 'btn btn-danger' %>
        <% else %>
            <p>ログインするとこのページからアカウントを削除できます。</p>
        <% end %>
        <%= link_to 'キャンセル', settings_path, class: 'btn btn-secondary' %>
        </div>
        
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% @page_title = "新規登録" %>

<div class="container mt-5">
  <div class="row">
    <div class="col-11 col-md-8 mx-auto">
      <div class="border col-12 rounded">

        <%= render 'shared/error_messages', object: @user %>

        <div class="col-10 mt-3 mb-3 mx-auto">
          <%= form_with model: @user, local: true do |f| %>
            <div class="mb-3">
            <%= f.label :name, "ユーザー名", class: "form-label" %>
            <%= f.text_field :name, class: "form-control" %>
            </div>
  
            <div class="mb-3">
            <%= f.label :email, "メールアドレス", class: "form-label" %>
            <%= f.email_field :email, class: "form-control" %>
            </div>
  
            <div class="mb-3">
            <%= f.label :password, "パスワード", class: "form-label" %>
            <%= f.password_field :password, class: "form-control" %>
            </div>
  
            <div class="mb-5">
            <%= f.label :password_confirmation, "パスワード確認", class: "form-label" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>

            <div class="mb-5">
            <%= f.submit '登録', class: 'btn btn-custom w-100' %>
            </div>

          </div>
        </div>
        <p>
          登録により<%= link_to 'プライバシーポリシー', privacy_policy_settings_path, class: 'link-custom' %> および
          <%= link_to '利用規約', terms_of_use_settings_path, class: 'link-custom' %> に同意したものとします。
        </p>
      </div>
      

  <% end %>
  </div>
  </div>
</div>