config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # パートナーの一覧ページとネスト
  resources :partners do
    member do
      delete :remove_image
      post :create_token  # 特定のパートナーに対する追加
      post :remove_share
    end
    collection do
      post :create_token  # 全てのパートナーに対する追加
    end
    resources :medications do
      member do
        delete :remove_image
      end
    end
    resources :foods do
      member do
        delete :remove_image
      end
    end
    resources :walks, only: %i[edit update]
  end

  # /complete_tutorial 等を独立したルートとして定義（本来partnersやsettingsと関係ないため）
  post 'complete_tutorial', to: 'partners#complete_tutorial', as: 'complete_tutorial'
  post 'reset_tutorial', to: 'settings#reset_tutorial', as: 'reset_tutorial'

  # ユーザー登録関連
  resources :users, only: %i[new create destroy]
  get 'users/delete', to: 'users#delete', as: :delete_user

  # ログイン・ログアウト関連
  resources :user_sessions, only: %i[new create destroy]
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # TOPページ（partners#indexに設定）
  root to: 'partners#index'

  # ログインページを明示的に設定
  get 'login', to: 'user_sessions#new'

  # 設定ページ
  resource :settings, only: %i[show update] do
    get :name_change, on: :collection
    get :news, on: :collection
    get :privacy_policy, on: :collection
    get :terms_of_use, on: :collection
  end

  # 開発環境でのメール設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :password_resets, only: %i[new create edit update]

  resources :email_changes, only: %i[new create update] do
    get 'confirm', on: :member
  end

  resources :remainders, only: [:update]

  namespace :api do
    resources :device_tokens, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]

  get 'share/:token', to: 'partner_shares#confirm', as: :confirm_share
  delete 'mutual_unshare/:user_id', to: 'partner_shares#mutual_unshare', as: :mutual_unshare
  delete 'other_partner_unshare/:user_id', to: 'partner_shares#other_partner_unshare', as: :other_partner_unshare
  delete 'my_partner_unshare/:user_id', to: 'partner_shares#my_partner_unshare', as: :my_partner_unshare

  # SNSログイン
  get '/auth/:provider/callback', to: 'sns_logins#create'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div id="flash-messages">
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-light custom-navbar d-flex justify-content-center">
        <ul class="navbar-nav d-flex flex-row justify-content-center">
            <li class="nav-item">
                <%= link_to settings_path, class: 'nav-link mx-3', id: 'settings-button' do %>
                    <i class="fa-solid fa-gear"></i> <span>設定</span>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to partners_path, class: 'nav-link mx-3' do %>
                    <i class="fa-solid fa-paw"></i> <span>パートナーリスト</span>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to logout_path, method: :delete, class: 'nav-link mx-3' do %>
                    <i class="fa-solid fa-door-open"></i> <span>ログアウト</span>
                <% end %>
            </li>
        </ul>
    </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-light custom-navbar justify-content-center">
    <% if (link = back_link(@partner)) %>
      <%= link %>
    <% end %>
    <!-- ページタイトルを文字列として表示 -->
    <span class="navbar-brand"><%= @page_title %></span>
  </nav>
</header>

app/views/shared/_qrcode_modal.html.erb
<div class="modal fade" id="qrCodeModal" tabindex="-1" aria-labelledby="qrCodeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="qrCodeModalLabel">QRコード</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
      </div>
      <div class="modal-body">
      <p>こちらのコードを読み取るとペット情報を共有できます！</p>
        <div id="qrCodeContainer" class="d-flex justify-content-center align-items-center" style="min-height: 200px;">
          <!-- QRコード挿入 -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_share_modal.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_label_id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%= modal_label_id %>"><%= modal_title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
      </div>
      <div class="modal-body">
        <p><%= modal_message %></p>
        
        <!-- 共有方法アイコン -->
        <div class="d-flex justify-content-center my-3">
          <!-- URLコピーアイコン -->
          <i class="fa-regular fa-clipboard share-icon" 
             onclick="handleShareClick('コピー', '<%= create_token_path %>'); return false;" 
             style="cursor: pointer; font-size: 1.5rem;" 
             title="コピー"></i>

          <!-- メール共有アイコン -->
          <i class="fa-regular fa-envelope ms-5 share-icon" 
             onclick="handleShareClick('メール', '<%= create_token_path %>'); return false;" 
             style="cursor: pointer; font-size: 1.5rem;" 
             title="メール"></i>

          <!-- LINE共有アイコン -->
          <i class="fa-brands fa-line ms-5 share-icon" 
             onclick="handleShareClick('LINE', '<%= create_token_path %>'); return false;" 
             style="cursor: pointer; font-size: 1.5rem;" 
             title="LINE"></i>

          <!-- QRコード共有アイコン -->
          <i class="fa-solid fa-qrcode ms-5 share-icon" 
             onclick="handleShareClick('QRコード', '<%= create_token_path %>'); return false;"  
             style="cursor: pointer; font-size: 1.5rem;" 
             title="QRコード"></i>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
      </div>
    </div>
  </div>
</div>


app/views/shared/_share_text_template.text.erb
こんにちは！ <%= user_name %>さんの PetNote から共有依頼が届いています！

PetNote にご登録の上、リンクにアクセスするとペット情報を共有できます。

<%= share_url %>

リンクの有効期限は発行から1時間以内です。期限が知れた場合は再度発行が必要です。
詳細についてはお問い合わせください。