config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # パートナーの一覧ページとネスト
  resources :partners do
    member do
      delete :remove_image
      post :create_token  # 特定のパートナーに対する追加
      post :remove_share
    end
    collection do
      post :create_token  # 全てのパートナーに対する追加
    end
    resources :medications do
      member do
        delete :remove_image
      end
    end
    resources :foods do
      member do
        delete :remove_image
      end
    end
    resources :walks, only: %i[edit update]
  end

  # /complete_tutorial 等を独立したルートとして定義（本来partnersやsettingsと関係ないため）
  post 'complete_tutorial', to: 'partners#complete_tutorial', as: 'complete_tutorial'
  post 'reset_tutorial', to: 'settings#reset_tutorial', as: 'reset_tutorial'

  # ユーザー登録関連
  resources :users, only: %i[new create destroy]
  get 'users/delete', to: 'users#delete', as: :delete_user

  # ログイン・ログアウト関連
  resources :user_sessions, only: %i[new create destroy]
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # TOPページ（partners#indexに設定）
  root to: 'partners#index'

  # ログインページを明示的に設定
  get 'login', to: 'user_sessions#new'

  # 設定ページ
  resource :settings, only: %i[show update] do
    get :name_change, on: :collection
    get :news, on: :collection
    get :privacy_policy, on: :collection
    get :terms_of_use, on: :collection
  end

  # 開発環境でのメール設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :password_resets, only: %i[new create edit update]

  resources :email_changes, only: %i[new create update] do
    get 'confirm', on: :member
  end

  resources :remainders, only: [:update]

  namespace :api do
    resources :device_tokens, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]

  get 'share/:token', to: 'partner_shares#confirm', as: :confirm_share
  delete 'mutual_unshare/:user_id', to: 'partner_shares#mutual_unshare', as: :mutual_unshare
  delete 'other_partner_unshare/:user_id', to: 'partner_shares#other_partner_unshare', as: :other_partner_unshare
  delete 'my_partner_unshare/:user_id', to: 'partner_shares#my_partner_unshare', as: :my_partner_unshare

  # SNSログイン
  get '/auth/:provider/callback', to: 'sns_logins#create'
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

# ユーザーのログインに関するコントローラーです。
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :auto_login_with_remember_me, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      handle_successful_login
    else
      handle_failed_login
    end
  end

  def destroy
    clear_session # クッキーがあれば削除処理を実行

    logout
    flash[:danger] = 'ログアウトしました'
    redirect_to login_path, status: :see_other
  end

  private

  def handle_successful_login
    ip_address = request.remote_ip
    session_retention(ip_address) if params[:remember_me] == '1'

    flash[:success] = 'ログインしました'
    redirect_to root_path
  end

  def handle_failed_login
    flash.now[:danger] = 'ログインに失敗しました'
    render :new, status: :unprocessable_entity
  end

  def session_retention(ip_address)
    session_data = Session.create_session_for(@user, ip_address)
    cookies.permanent.signed[:session_id] = session_data[:session].id
    cookies.permanent[:remember_token] = session_data[:token]
  end

  def clear_session
    if (session_id = cookies.signed[:session_id])
      session = Session.find_by(id: session_id)
      session&.destroy
      cookies.delete(:session_id)
      cookies.delete(:remember_token)
    end
  end
end

app/helpers/user_sessions_helper.rb
# frozen_string_literal: true

# ユーザーのログインについて使用されるヘルパーメソッドを提供します。
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-md-8 mx-auto">
    
      <h1 class="my-4 text-center" style="color: #444444; font-family: Arial, sans-serif;">ペット手帳</h1>

      <div class="row">
      <div class="border col-12 rounded">
        <div class="row">
        <div class="col-10 mt-3 mb-3 mx-auto">
          <%= form_with url: login_path, local: true do |form| %>
            <div class="mb-3">
              <%= form.label :email, 'メールアドレス', class: 'form-label' %>
              <%= form.email_field :email, class: 'form-control', id: 'email', placeholder: 'メールアドレスを入力' %>
            </div>
            
            <div class="mb-2">
              <%= form.label :password, 'パスワード', class: 'form-label' %>
              <%= form.password_field :password, class: 'form-control', id: 'password', placeholder: 'パスワードを入力' %>
            </div>

            <div class="form-check mb-4">
              <%= form.check_box :remember_me, class: 'form-check-input', id: 'remember_me' %>
              <%= form.label :remember_me, 'ログイン状態を保持する', class: 'form-check-label' %>
            </div>
            
            <div class="mb-3">
              <%= form.submit 'ログイン', class: 'btn btn-custom w-100' %>
            </div>
          <% end %>
            
            <div class="mb-5">
              <%= link_to '新規登録', new_user_path, class: 'link-custom' %>
              <%= link_to 'パスワードを忘れましたか？', new_password_reset_path, class: 'link-custom' %>
            </div>
        </div>
        </div>
      </div>
        <p>
          <%= link_to 'プライバシーポリシー', privacy_policy_settings_path, class: 'link-custom' %> および
          <%= link_to '利用規約', terms_of_use_settings_path, class: 'link-custom' %> はこちら。
        </p>


              <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                <%= link_to '<i class="fa-brands fa-twitter"></i> Xでログイン'.html_safe, '/auth/twitter', class: 'btn btn-outline-secondary', style: 'width: 100%; max-width: 300px;' %>
                <% if Rails.env.development? %>
                <%= link_to '<i class="fa-brands fa-google"></i> Googleアカウントでログイン'.html_safe, '/auth/google_oauth2', class: 'btn btn-outline-secondary', style: 'width: 100%; max-width: 300px;' %>
                <%= link_to '<i class="fa-brands fa-facebook-f"></i> Facebookでログイン'.html_safe, '/auth/facebook', class: 'btn btn-outline-secondary', style: 'width: 100%; max-width: 300px;' %>
                <% end %>
              </div>


      </div>
    </div>
  </div>
</div>